server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user
    username: postgres
    password: Amreen2497
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # <- Changed from validate to update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: INFO
    com.getwork.user: DEBUG
